name: Deploying react project

on:
  - push
  - workflow_dispatch

permissions:
    contents: read
jobs:
  cloning_code:
    runs-on: ubuntu-latest
    # cloning the repo
    # method 1 using expression context . context means variable or function we use what github provides
    steps:
      - name: Get the Code
        run: |
          echo cloning the repo
          echo ${{ toJson(github)}}
          git clone https://github.com/${{github.repository}}.git
